### ISSUE TITLE
Set up production env

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#23]

**Comment by m1guelpf** [comment]
I have a shared hosting I use for most projects, I can setup autodeployment if you want. Also, maybe we can use the Laracon Online .co domain...

**Comment by assertchris** [comment]
I'm also happy to put it up on Forge...

**Comment by assertchris** [comment]
borrowmytopic.co

**Comment by m1guelpf** [comment]
@assertchris Where are you hosting it? Also, maybe we should setup asset versioning, move asset generation to the server and stop tracking compiled files...

**Comment by assertchris** [comment]
Hosting on Forge and DigitalOcean (AMS). Those are good ideas.
