### ISSUE TITLE
Submit topics

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#31]
so far this topics module is really a "conference talk" module; it ignores and doesn't allow (or is strangely worded) for other sources like blog posts, videos, videos with code samples...

I think we should step back and make sure we have a clean design that thinks about all of those

**Comment by assertchris** [comment]
They are fields that map to my understanding of conference talk submission. Happy to adjust fields and help text to make it less conference talk specific.

**Comment by jrmadsen67** [comment]
no reason to hold it up - looks fine for what's here, second round to expand like we chatted about
