### ISSUE TITLE
Submit topic presentation feedback

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#32]
I'm not sure where the relevance of this whole table is?

If a speaker sees a talk they like, they will reform their own version of it. I suppose feedback is helpful in doing that..?

**Comment by assertchris** [comment]
Indeed, and also for publishers/organisers to see what the response was to the talk. It's the same reason why there's a `additional` field in Presentations – to point out reasons/things that went really well or really poorly.
