### ISSUE TITLE
Submit topic presentations

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#33]
is this different from "Submit a presentation"?

**Comment by assertchris** [comment]
Topic is the talk/blog/article e.g. Asynchronous PHP. Presentation is an instance of it, e.g. at Zendcon 2015.

**Comment by jrmadsen67** [comment]
what is the purpose of tracking that?

**Comment by assertchris** [comment]
Speakers can see where the talk has been submitted to before. If I submitted a topic to Zendcon, last year, they might not think it's such a good idea to submit the same topic to the same conference this year.

**Comment by jrmadsen67** [comment]
I'm okay with this (no harm in collecting), but I really want to stress
that my reason for making this app is to help the thousands of weekly &
monthly meetups who can never get any presentations and die a slow death.

I think conferences can take care of themselves, and if you want to present
at a conference you'd best be passionate enough about an idea to come up
with it yourself. I'm not primarily interested in helping  former
conference presenters keep their old talks alive via surrogates.

**Comment by assertchris** [comment]
> former conference presenters keep their old talks alive via surrogates.

What a strange way to phrase that. Keeping the topic alive is a purpose of this app, in as much as the topic has teeth and new speakers might want to run with it. 

I agree that meet-ups could use all the help they can get. Remembering which talks were had at the local conference last year might also be a good way to bring back those speakers or avoid repeating stale content. It's also a way of gathering speaker info for things like introductions or to make connections. "x speaker spoke at the same conference as y speaker. Perhaps they could introduce us to y speaker so we could have them on next month..."

**Comment by jrmadsen67** [comment]
yeah, see - that's why I wanted to slow down and talk.

" Keeping the topic alive is a purpose of this app " is not even remotely
the idea of this app from my perspective. We have different things in mind,
which was becoming obvious to me as I reviewed what you are setting up.

My 100% concern is helping small meetups. There are a lot of places where
there are very few "local conferences" & nothing big enough to bring in
special speakers.

You're looking at this whole thing at a much "higher" level than I am. I'm
thinking about how can I help my local English language meetups in the
Osaka area that have 10-15 people on a good night and beg every month for
someone to stand up in front and say something.

I don't think our two ideas are necessarily at odds for being in the same
site, but I don't think we are on the same page for what we want to make
this for

**Comment by assertchris** [comment]
I see what you're saying. What do we need to change to help that meet-up in Osaka?

**Comment by jrmadsen67** [comment]
I don't think so much, tbh. I don't see anything you've added that
interferes with that - I was just afraid we were drifting off in different
directions.

we should prolly make a few tweaks to the topics table/screens now rather
than later so they are more generic in nature.

as more of an FYI, a lot of the people I have in mind are more likely to
see blog posts or YouTube videos as sources than to actually attend a
conference where they hear a talk they'd like to borrow, simply from
acessibility
