### ISSUE TITLE
Add the ability to hide topics by adding a timestamp

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#34]
why a timestamp (other than I like timestamps as flags as well)?

I mean, is there a desire to close the topic for a certain time or something? what's the idea behind it?

**Comment by assertchris** [comment]
The way these get `hidden_at` timestamps is for someone to report the topic, us to investigate it, determine that the topic is inappropriate (plagerised, a giant ASCII picture of a penis etc.), and then add a timestamp in the DB. It's not an automatic thing, at this stage, and all it is supposed to do is hide the topic from search.

Other than the benefit of knowing when the topic was hidden; there is no other reason why I haven't used a boolean flag.

**Comment by jrmadsen67** [comment]
ah, I see. I thought the author might be "taking it off the shelf" for a
while for some reason

**Comment by assertchris** [comment]
I want to add a banner to the top of the talk edit screen to say something like; "this talk has been hidden from the main site for x reason, please contact an administrator".
