### ISSUE TITLE
Profile link doesn't work when user doesn't have a handle

### ISSUE THREAD

**Issue by m1guelpf** [assertchris/borrow-my-topic#40]
For some reason the profile link on the deplyed site links to `/profile` instead of `/profile/{handle}`. The code seems to be :+1:... So I guess this could be a view cache problem. @assertchris Are you clearing view cache on deploy?

**Comment by assertchris** [comment]
I wasn't, but I have made it so now! :)

**Comment by m1guelpf** [comment]
The link still doesn't work for me. You may have to trigger a deploy or SSH and manually clear cache

**Comment by assertchris** [comment]
I ssh'd in and cleared the cache by hand. I have tested the link from the dropdown and from the search results -> topics page. Where are you seeing the incorrect link?

**Comment by m1guelpf** [comment]
@assertchris ![](https://m1guelpf.joined-the.club/NmVeNTutr.png)

**Comment by assertchris** [comment]
I cannot reproduce that. I suggest clearing your browser cache.

**Comment by m1guelpf** [comment]
@assertchris Managed to fix it. It seems like I hadn't created a handle, so the handle was null. I'd suggest hiding that link for people who still haven't created a handle or make it a registration step.

**Comment by assertchris** [comment]
Oh, good catch!

**Comment by assertchris** [comment]
Added project: https://github.com/assertchris/borrow-my-topic/issues/41.
