### ISSUE TITLE
Add under-represented group settings

### ISSUE THREAD

**Issue by jrmadsen67** [assertchris/borrow-my-topic#8]
1) what is `from_under_represented_group_additional` used for?

**Comment by assertchris** [comment]
<img width="793" alt="screen shot 2018-03-11 at 18 54 03" src="https://user-images.githubusercontent.com/200609/37276913-ddfaf77a-25eb-11e8-94a8-6e96ed34f843.png">

**Comment by jrmadsen67** [comment]
cool - page looks good

**Comment by m1guelpf** [comment]
This is done, can we close it?

**Comment by jrmadsen67** [comment]
yes, anything moved to done can be closed

On Mon, Mar 12, 2018 at 8:50 PM, Miguel Piedrafita <notifications@github.com
